In [ ]:
# importing required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#### Reading User data set

In [ ]:

df_user = pd.read_csv('https://raw.githubusercontent.com/ammishra08/Simplilearn/main/EDA/BX-Users.csv' , encoding = 'latin-1')

In [ ]:
# checking the top 5 rows
df_user.head()

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [ ]:
# checking the null values
df_user.isnull().sum()

user_id          0
Location         1
Age         110763
dtype: int64

In [ ]:
#dropping the null values
df_user.dropna(inplace = True)

In [ ]:
df_user.isnull().sum()

user_id     0
Location    0
Age         0
dtype: int64

In [ ]:
df_user.shape


(168096, 3)

#### Reading books data

In [ ]:
df_books = pd.read_csv('https://raw.githubusercontent.com/ammishra08/Simplilearn/main/EDA/BX-Books.csv', encoding = 'latin-1')

In [ ]:
df_books.shape

(271379, 5)

In [ ]:
df_books.describe()

isbn      book_title      book_author year_of_publication  \
count      271376          271376           271376              271376   
unique     271376          242148           102041                 202   
top     195153448  Selected Poems  Agatha Christie                2002   
freq            1              27              632               17144   

        publisher  
count      271376  
unique      16822  
top     Harlequin  
freq         7535

In [ ]:
df_books.isnull().sum()

isbn                   0
book_title             0
book_author            1
year_of_publication    0
publisher              2
dtype: int64

In [ ]:
df_books.dropna(inplace = True)

In [ ]:
df_books.isnull().sum()

isbn                   0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

In [ ]:
df_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

#### Reading ratings data

In [ ]:
df_rating = pd.read_csv('https://raw.githubusercontent.com/ammishra08/Simplilearn/main/EDA/BX-Book-Ratings.csv', encoding='latin-1', nrows=10000)

In [ ]:
df_rating.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [ ]:
# merging df_rating and df_books on isbn column to make single dataframe
df = pd.merge(df_rating, df_books, on = 'isbn') 

In [ ]:
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  
0                2002            Ballantine Books  
1                2001                      Heinle  
2                1996                Warner Books  
3                1996                Warner Books  
4                1999  Cambridge University Press

In [ ]:
df.shape

(8701, 7)

In [ ]:
df.isnull().sum()

user_id                0
isbn                   0
rating                 0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

In [ ]:
# number of unique users and books
no_of_books = df.isbn.nunique() 
print('number of unique books in the data set: ',no_of_books)
no_of_users = df.user_id.nunique() 
print('number of unique users in the data set: ',no_of_users)

number of unique books in the data set:  8051
number of unique users in the data set:  828


In [ ]:
# making the list of unique books and users
user_list = list(df.user_id.unique())
book_list = list(df.isbn.unique())

In [ ]:
user_list[0:5]

[276725, 276726, 276727, 278418, 276729]

In [ ]:
book_list[0:5]

['034545104X', '155061224', '446520802', '052165615X', '521795028']

In [ ]:
# Convert ISBN variables to numeric numbers in the correct order
def get_isbn_numeric_id(isbn):
    itemindex = book_list.index(isbn)
    return itemindex

In [ ]:
df['isbn_id'] = df['isbn'].apply(get_isbn_numeric_id)
print(df.isbn_id)

0          0
1          1
2          2
3          2
4          3
        ... 
8696    8046
8697    8047
8698    8048
8699    8049
8700    8050
Name: isbn_id, Length: 8701, dtype: int64


In [ ]:
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  isbn_id  
0                2002            Ballantine Books        0  
1                2001                      Heinle        1  
2                1996                Warner Books        2  
3                1996                Warner Books        2  
4                1999  Cambridge University Press        3

In [ ]:
# Convert user_id variables to numeric numbers in the correct order
def get_user_numeric_id(user_id):
    itemindex = user_list.index(user_id)
    return itemindex

In [ ]:
df['user_id_order'] = df['user_id'].apply(get_user_numeric_id)
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  isbn_id  user_id_order  
0                2002            Ballantine Books        0              0  
1                2001                      Heinle        1              1  
2                1996                Warner Books        2              2  
3                1996                Warner Books        2              3  
4                1999  Cambridge University Press        3              4

In [ ]:
#Reindexing the columns
reindex_order = ['user_id_order', 'isbn_id', 'rating', 'book_title', 'book_author','year_of_publication','publisher','isbn','user_id']
df = df.reindex(columns= reindex_order)
df.head()

user_id_order  isbn_id  rating            book_title      book_author  \
0              0        0       0  Flesh Tones: A Novel       M. J. Rose   
1              1        1       5      Rites of Passage       Judith Rae   
2              2        2       0          The Notebook  Nicholas Sparks   
3              3        2       0          The Notebook  Nicholas Sparks   
4              4        3       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher        isbn  user_id  
0                2002            Ballantine Books  034545104X   276725  
1                2001                      Heinle   155061224   276726  
2                1996                Warner Books   446520802   276727  
3                1996                Warner Books   446520802   278418  
4                1999  Cambridge University Press  052165615X   276729

#### splitting the data into training data and testing data

In [ ]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df, test_size= 0.3)

In [ ]:
df_train.shape

(6090, 9)

In [ ]:
df_test.shape

(2611, 9)

In [ ]:
#user-book matrix for training
train_data_matrix = np.zeros((no_of_users,no_of_books ))
for line in df_train.itertuples():
  train_data_matrix[line[1]-1, line[2]-1] = line[3]

In [ ]:
# user-book matrix for training
test_data_matrix = np.zeros((no_of_users,no_of_books ))
for line in df_test.itertuples():
  test_data_matrix[line[1]-1, line[2]-1] = line[3]

In [ ]:
train_data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# importing pair-wise distance
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric = 'cosine')
item_similarity = pairwise_distances(train_data_matrix.T, metric = 'cosine') 

In [ ]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [ ]:
item_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

#### Prediction

In [ ]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #You use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis]) 
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])     
    return pred

In [ ]:
item_prediction = predict(train_data_matrix, item_similarity, type='item')
user_prediction = predict(train_data_matrix, user_similarity, type='user')

In [ ]:
print(item_prediction)

[[0.         0.00062112 0.0006212  ... 0.00062135 0.00062112 0.00062112]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.05565217 0.05565217 0.05565909 ... 0.05567292 0.05565217 0.05565217]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
print(user_prediction)


[[-0.00114326 -0.00114326  0.00248431 ...  0.00973945 -0.00114326
  -0.00114326]
 [ 0.0042809  -0.00176505  0.00186252 ...  0.00911766 -0.00176505
  -0.00176505]
 [ 0.05999506  0.05394735  0.05757598 ...  0.06483323  0.05394735
   0.05394735]
 ...
 [ 0.0042809  -0.00176505  0.00186252 ...  0.00911766 -0.00176505
  -0.00176505]
 [ 0.0042809  -0.00176505  0.00186252 ...  0.00911766 -0.00176505
  -0.00176505]
 [ 0.0042809  -0.00176505  0.00186252 ...  0.00911766 -0.00176505
  -0.00176505]]


#### Evaluation

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(prediction, ground_truth):
    prediction = prediction[ground_truth.nonzero()].flatten() 
    ground_truth = ground_truth[ground_truth.nonzero()].flatten()
    return sqrt(mean_squared_error(prediction, ground_truth))

In [ ]:
print('User-based CF RMSE: ', rmse(user_prediction, test_data_matrix))
print('Item-based CF RMSE: ',rmse(item_prediction, test_data_matrix))

User-based CF RMSE:  7.680408945197645
Item-based CF RMSE:  7.6797845404884475
